### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by Julian** [python-jsonschema/hypothesis-jsonschema#98]
Hello friend. Hope all's well.

In the past ~2 years I moved `jsonschema` into [an org](https://github.com/python-jsonschema/), in an attempt both to try to distance it from me and make it "more clearly collective", but also to build up a bit more of a surrounding ecosystem, first via @sirosen's [better CLI](https://github.com/python-jsonschema/check-jsonschema).

Do you have any desire to join / bring this tool into it? I'd love to give it more exposure -- not that it needs me to do it certainly, but in whatever small way, by calling it "official", and hopefully using it upstream in the library (which of course can be done regardless).

(n.b. I have future even more elaborate plans with [bowtie using this library](https://github.com/python-jsonschema/bowtie) but those are still only a glimmer in my eye until it's done, but already looking forward to it.)

Anyhow. Absolutely 0 hard feelings if you'd prefer not to! And I of course wouldn't ask for any oversight whatsoever, so everything exactly as-is. Just figured I'd extend the ask.

Be well! (And stay in touch :)

**Comment by Zac-HD** [comment]
Heya!  I'm going well, moved to SF earlier to work at [Anthropic](https://www.anthropic.com/) and it's a dream job 🤩  If you're ever over this way, I'd love to catch up in person too.

I'd actually be delighted to join in and move the repo upstream!  It's [been pretty inactive since mid-2020](https://github.com/Zac-HD/hypothesis-jsonschema/graphs/contributors), since I've put it into maintainence-only mode - further improvements would mostly require some level of rewrite, and while I'm not personally interested in doing that I'd be delighted to mentor someone who was.  Upstreaming, and use in various upstream plans, seems like a great way to find a new co-maintainer.

(said improvements: better canonicalization, support for alternative validator libraries, understanding specific version of the jsonschema spec, handling recursive references, handling remote references.  Other issues describe the desired solutions)

Next steps then are, I think, you add me to the org and I move the repo?

**Comment by Julian** [comment]
> moved to SF earlier to work at [Anthropic](https://www.anthropic.com/) and it's a dream job 🤩 If you're ever over this way, I'd love to catch up in person too.

Oh wow! That's indeed huge, congrats! I'm traveling for the summer but there's indeed a decent shot I'll make it out to SF in the next few months :). Will look you up.

And awesome! All makes sense I think, really glad to hear it. I sent you an invite :), hooray.

**Comment by Zac-HD** [comment]
Aaaand, done :shipit: 

This is going to be fun, and I'm looking forward to catching up when that happens!

**Comment by Julian** [comment]
Hooray, sent out a bit of PR to see if it attracts anyone interested in the mentoring offer: https://twitter.com/JulianWasTaken/status/1554740332180504577 hope that's OK :)
